# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7ac6b249c8a11698d14be16a704ed1e9f55140959a555cd80c16433b338d1fe1e10627690e05faf79b208435e47264df0c3c00209154b11c209f5b104c1aa2e

test:
  secret_key_base: d5f4b5f30b18f85dbd2718576bfbc901f6658a9aa256474d948c73f5c3f62beadd09661671586acc0088325b34af0d2eda51a2c737fecc48c28596f8c9b59dfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
